steps:
  # 建構 Docker 映像
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vocab-ai-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vocab-ai-backend:latest'
      - '.'

  # 推送映像到 Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vocab-ai-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vocab-ai-backend:latest'

  # 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'replace'
      - 'configs/service.yaml' # <-- 指向我們的設定檔
      - '--image'
      - 'gcr.io/$PROJECT_ID/vocab-ai-backend:$COMMIT_SHA' # <-- 動態傳入映像
      - '--region'
      - 'asia-east1'

# 映像儲存選項
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# 替代變數 (可在觸發器中設定)
substitutions:
  _SERVICE_NAME: 'vocab-ai-backend'
  _REGION: 'asia-east1'