substitutions:
  _REGION: asia-east1
  _SERVICE_NAME: vocab-ai-backend
  _REPO: gcr.io/${PROJECT_ID}/vocab-ai-backend

steps:
  # 1) Build & push image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REPO}:${SHORT_SHA}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REPO}:${SHORT_SHA}

  # 2) 產生實際要套用的 YAML（把占位字替換掉）
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        sed "s|IMAGE_URL_PLACEHOLDER|${_REPO}:${SHORT_SHA}|g" configs/service.yaml > service.rendered.yaml
        echo "==== Rendered service.yaml ===="
        cat service.rendered.yaml

  # 3) 用 Knative YAML 直接替換（讀取 YAML 並部署）
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - services
      - replace
      - service.rendered.yaml
      - --region=${_REGION}
      - --platform=managed
      - --quiet
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - ${_REPO}:${SHORT_SHA}