# configs/service.yaml
# 此檔案由 `gcloud run services replace` 指令使用，定義了 Cloud Run 服務的最終狀態。
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: memwhiz-backend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '1'
      
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: IMAGE_URL_PLACEHOLDER
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          env:
            - name: ENVIRONMENT
              value: 'production'
            # --- 系統運行模式 ---
            - name: BOT_MODE
              value: 'webhook'
            - name: START_API
              value: 'true'
            # 關閉 FastAPI 進程內的 Telegram 橋接，避免重複附掛 Router
            - name: ENABLE_TELEGRAM_BRIDGE
              value: '0'

            # --- config.yaml.template 的內容被映射到環境變數 ---

            # database
            - name: DATABASE_DB_PATH
              value: 'memwhiz.db'

            # access_control (TELEGRAM_USER_IDS 現在從 Secret Manager 讀取)
            - name: ACCESS_CONTROL_ENABLE_WHITELIST
              value: 'true'
            - name: ACCESS_CONTROL_LOCAL_TEST_MODE
              value: 'false'
            - name: ACCESS_CONTROL_WHITELIST_USERS
              valueFrom:
                secretKeyRef:
                  name: telegram_user_ids
                  key: latest

            # mini_app
            - name: MINI_APP_URL
              value: 'https://your-domain.com'
            - name: MINI_APP_ENABLE_TELEGRAM_AUTH
              value: 'true'
            - name: MINI_APP_SESSION_TIMEOUT
              value: '86400'

            # webhook
            - name: WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: webhook_url
                  key: latest

            # ai_services
            - name: AI_SERVICES_PROVIDER
              value: 'google'

            # prompts
            - name: PROMPTS_SIMPLE_EXPLANATION
              value: |
                請使用繁體中文回覆，並且務必回覆有效的 JSON 格式。你是一位專業的英文教學助理。請針對我提供的單字，提供以下 JSON 格式的完整資訊：

                單字：{word}

                請回覆以下 JSON 格式（請注意：回覆必須是有效的 JSON，不要包含任何其他文字）：
                {{
                  "word": "{word}",
                  "pronunciations": ["音標1", "音標2"],
                  "definitions": [
                    {{
                      "part_of_speech": "詞性（如：noun, verb, adjective）",
                      "meanings": [
                        {{
                          "definition": "中文定義1",
                          "context": "使用語境或註釋"
                        }},
                        {{
                          "definition": "中文定義2（如有多個意思）",
                          "context": "使用語境或註釋"
                        }}
                      ]
                    }},
                    {{
                      "part_of_speech": "其他詞性（如果有）",
                      "meanings": [
                        {{
                          "definition": "該詞性的中文定義",
                          "context": "使用語境"
                        }}
                      ]
                    }}
                  ],
                  "examples": ["例句1", "例句2", "例句3"],
                  "synonyms": ["同義詞1", "同義詞2"],
                  "antonyms": ["反義詞1", "反義詞2"],
                  "memory_tips": "記憶技巧或字源解釋"
                }}
            - name: PROMPTS_DEEP_LEARNING
              value: |
                請深度分析英文單字 "{word}"，使用繁體中文回覆，包含詞源、記憶法、搭配用法等深入內容。請回覆 JSON 格式：
                {{
                  "word": "{word}",
                  "pronunciations": ["/{word}/"],
                  "etymology": {{"origin": "詞彙來源和歷史", "root_analysis": "字根字首字尾分析", "related_words": ["相關詞彙"]}},
                  "definitions": [{{"part_of_speech": "主要詞性", "meanings": [{{"definition": "詳細中文定義", "context": "使用語境", "formality": "正式程度", "usage_notes": "特殊用法"}}]}}],
                  "collocations": {{"common_phrases": ["常見片語"], "verb_combinations": ["動詞搭配"], "adjective_combinations": ["形容詞搭配"], "preposition_combinations": ["介詞搭配"]}},
                  "examples": [{{"sentence": "英文例句", "translation": "中文翻譯", "context": "使用情境"}}],
                  "synonyms": [{{"word": "近義詞", "difference": "細微差別"}}],
                  "antonyms": ["反義詞"],
                  "memory_strategies": {{"visual": "視覺記憶法", "association": "聯想記憶", "word_formation": "詞彙構成記憶", "story": "故事記憶法"}},
                  "cultural_notes": "文化背景和使用注意事項",
                  "difficulty_level": "學習難度",
                  "frequency": "使用頻率"
                }}
            - name: PROMPTS_QUICK_TRANSLATION
              value: |
                請快速翻譯以下內容（簡潔版本）：

                "{text}"

                請回覆 JSON 格式：
                {{
                  "original_text": "{text}",
                  "detected_language": "原文語言（中文/英文/日文等）",
                  "primary_translation": "主要翻譯",
                  "alternative_translations": ["替代翻譯1", "替代翻譯2"],
                  "key_words": [
                    {{
                      "original": "重要詞彙",
                      "translation": "翻譯",
                      "note": "簡短說明"
                    }}
                  ]
                }}

                請確保：
                1. 翻譯準確且自然
                2. 提供2-3個替代翻譯
                3. 標註2-3個關鍵詞彙
                4. 保持回應簡潔
            - name: PROMPTS_DEEP_TRANSLATION
              value: |
                請精準翻譯以下內容，並提供詳細的語言分析：

                "{text}"

                請回覆 JSON 格式：
                {{
                  "original_text": "{text}",
                  "detected_language": "原文語言（中文/英文）",
                  "translations": {{
                    "primary_translation": "主要翻譯（最準確和自然的翻譯）",
                    "alternative_translations": [
                      "替代翻譯1（不同風格或語境）",
                      "替代翻譯2（更正式或更口語的版本）"
                    ],
                    "literal_translation": "直譯版本（幫助理解語法結構）"
                  }},
                  "language_analysis": {{
                    "grammar_structure": [
                      {{
                        "original_part": "原文片段",
                        "translation_part": "對應翻譯",
                        "grammar_note": "語法結構說明"
                      }}
                    ],
                    "cultural_context": {{
                      "cultural_differences": "文化差異說明",
                      "usage_context": "使用語境和場合",
                      "cultural_adaptation": "文化適應建議"
                    }},
                    "language_difficulty": "翻譯難度（初級/中級/高級）",
                    "key_challenges": ["翻譯挑戰1", "翻譯挑戰2"]
                  }},
                  "vocabulary_breakdown": [
                    {{
                      "original_word": "原文詞彙",
                      "translated_word": "翻譯詞彙",
                      "part_of_speech": "詞性",
                      "usage_notes": "用法說明",
                      "common_alternatives": ["其他常見翻譯"]
                    }}
                  ],
                  "grammar_comparison": {{
                    "sentence_structure": "兩種語言的句子結構比較",
                    "word_order": "語序差異說明",
                    "tense_aspect": "時態和語態比較"
                  }},
                  "usage_examples": [
                    {{
                      "scenario": "使用場景",
                      "example_original": "原文例句",
                      "example_translation": "翻譯例句",
                      "context_note": "語境說明"
                    }}
                  ],
                  "learning_tips": {{
                    "translation_strategies": "翻譯策略建議",
                    "common_mistakes": "常見錯誤提醒",
                    "memory_aids": "記憶輔助方法"
                  }}
                }}

                請確保：
                1. 翻譯準確且符合目標語言的表達習慣
                2. 考慮文化背景和語境差異
                3. 提供語法結構的對比分析
                4. 解釋重要詞彙的選擇原因
                5. 給出實用的學習建議
            - name: PROMPTS_SENTENCE_ANALYSIS_OPTIMIZATION
              value: |
                請使用繁體中文深度分析並優化以下英語句子：
                "{sentence}"
                請提供完整的句子分析和優化建議，回覆 JSON 格式：
                {{
                  "original_sentence": "{sentence}",
                  "analysis": {{
                    "sentence_type": "句型類別（如：簡單句、複合句、複雜句）",
                    "grammar_structure": [
                      {{
                        "component": "語法成分（如：主語、謂語、賓語、定語、狀語）",
                        "text": "對應的文字片段",
                        "explanation": "中文解釋這個成分的作用和特點"
                      }}
                    ],
                    "tense_analysis": {{
                      "tense_name": "時態名稱",
                      "tense_form": "時態形式說明",
                      "usage_explanation": "為什麼使用這個時態"
                    }},
                    "complexity_level": "句子複雜度（初級/中級/高級）"
                  }},
                  "grammar_issues": [
                    {{
                      "type": "錯誤類型（如：語法錯誤、標點錯誤、用詞不當）",
                      "location": "錯誤位置的文字",
                      "description": "錯誤描述",
                      "correction": "修正建議",
                      "explanation": "為什麼需要修正"
                    }}
                  ],
                  "optimization_suggestions": [
                    {{
                      "type": "優化類型（如：語言風格、詞彙選擇、句子結構）",
                      "original_part": "原始片段",
                      "suggested_improvement": "建議改進",
                      "reason": "改進原因和好處",
                      "example": "改進後的完整句子"
                    }}
                  ],
                  "vocabulary_enhancements": [
                    {{
                      "original_word": "原始用詞",
                      "suggested_alternatives": ["替代選項1", "替代選項2"],
                      "context_explanation": "在此語境下的最佳選擇說明"
                    }}
                  ],
                  "style_improvements": {{
                    "formality_level": "正式程度建議（正式/半正式/非正式）",
                    "tone_suggestions": "語調建議",
                    "clarity_score": "清晰度評分（1-10）",
                    "overall_assessment": "整體評價和主要改進方向"
                  }},
                  "final_optimized_versions": [
                    "優化版本1（保持原意，語法和風格優化）",
                    "優化版本2（更簡潔的表達）",
                    "優化版本3（更正式或更口語的版本）"
                  ],
                  "learning_tips": "針對此句子的學習重點和記憶建議"
                }}
                請確保：
                1. 準確識別所有語法成分和結構
                2. 指出任何語法或用詞問題
                3. 提供具體、實用的優化建議
                4. 解釋每個建議的原因
                5. 提供多個優化版本供參考

            # --- 從 Secret Manager 引用 Secrets ---
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram_bot_token
                  key: latest
            - name: AI_SERVICES_GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google_api_key
                  key: latest
            - name: AI_SERVICES_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai_api_key
                  key: latest
            - name: AI_SERVICES_DEEPSEEK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: deepseek_api_key
                  key: latest
            - name: DATABASE_GCS_BUCKET
              value: 'memwhiz-db'
